apiVersion: v1
kind: ReplicationController
metadata: 
  name: myweb-rc
spec: 
  replicas: 3
  selector: 
    env: production
  template: 
    metadata:
      name: myweb-pod3 
      labels: 
        env: production
      name: myweb-pod
    spec: 
      containers: 
        - name: myweb-cont
          image: httpd
          
#commands for launching,deleting and checking status
#kubectl create -f rc.yml
#kubectl get all
#kubectl get pods --show-labels
#kubectl get pods -l "env=production"
#kubectl describe rc/myweb-rc
#kubectl delete all --all