apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myweb-rs
spec: 
  replicas: 3
  selector: 
    matchExpressions:
       - { key: env, operator: In, values: [ production] }
       - { key: region, operator: In, values: [ IN ] }
  template: 
    metadata: 
      name: myweb-pod
      labels: 
        dc: "5"
        env: production
        region: IN
    spec: 
      containers: 
        - name: myweb-con
          image: httpd
    
#commands for launching,deleting and checking status    
#kubectl get pods
#kubectl get rs
#kubectl describe rs/myweb-rs
#kubectl get pods -l "env in (production),region in (IN)"
#kubectl get pods -l 'env in (production),region in (IN)'
#kubectl delete pods myweb-rs-4625n
#kubectl get pods -l "env in (production),region in (IN)"
#kubectl get delete rs/myweb-rs           