apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    env: testing
    region: IN
spec:
  containers:
  - name: mysql-cont
    image: mysql:5.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecure
            key: rootpass
      - name: MYSQL_USER
        value: jagadeesh
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecure
            key: userpass
      - name: MYSQL_DATABASE
        value: mydb    
    volumeMounts:
      - name: db-vol
        mountPath: /var/lib/mysql   
  volumes:
  - name: db-vol
    persistentVolumeClaim:
      claimName: web-pvc1